// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-fuNkgFKuS2Ij1D9d8Fx8mog-WukFiQ',
    appId: '1:159470730246:web:72a6efe4f7e9c3433f9787',
    messagingSenderId: '159470730246',
    projectId: 'wffl-52c4d',
    authDomain: 'wffl-52c4d.firebaseapp.com',
    databaseURL:
        'https://wffl-52c4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wffl-52c4d.appspot.com',
    measurementId: 'G-M52MGZ9FP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq34cYh8qK6k-hj_oJHKPmLtHlhr5FirU',
    appId: '1:159470730246:android:c649e236c008267c3f9787',
    messagingSenderId: '159470730246',
    projectId: 'wffl-52c4d',
    databaseURL:
        'https://wffl-52c4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wffl-52c4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSSFGAOWZ2kHaiACttYPHTE81rRHysErk',
    appId: '1:159470730246:ios:a3881a824e2a7acb3f9787',
    messagingSenderId: '159470730246',
    projectId: 'wffl-52c4d',
    databaseURL:
        'https://wffl-52c4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wffl-52c4d.appspot.com',
    iosClientId:
        '159470730246-65ujn0p4j28csb6oip456bv0o31m675f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSSFGAOWZ2kHaiACttYPHTE81rRHysErk',
    appId: '1:159470730246:ios:caa9fd77e4585f773f9787',
    messagingSenderId: '159470730246',
    projectId: 'wffl-52c4d',
    databaseURL:
        'https://wffl-52c4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wffl-52c4d.appspot.com',
    iosClientId:
        '159470730246-ad3s2ger8g5u9tqekdq8bjgmta7l2phf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseSample.RunnerTests',
  );
}
